name: Neural Roots Core API - Continuous Integration

on:
  push:
    branches:
      - main
      
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: config
    steps:
      - name: Set up environment variables
        run: |
          echo "POSTGRES_USER=${{ vars.POSTGRES_DB_USERNAME }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ vars.POSTGRES_DB_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ vars.POSTGRES_DB_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ vars.POSTGRES_DB_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_HOST=${{ vars.POSTGRES_DB_HOST }}" >> $GITHUB_ENV

      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/neural-roots-core-fastapi:latest
